### ISSUE TITLE
Setting 0 stock for item in Opencart does not reflect in shopee

### ISSUE THREAD

**Issue by nmcapule** [nmcapule/oclz#8]
It reflects on Lazada though.

Project: ciruitkeo, sku 2325

**Comment by archercode** [comment]
Traceback (most recent call last):
  File "../main.py", line 112, in <module>
    COMMAND_LOOKUP[args.mode](config, args)
  File "../main.py", line 24, in CommandSync
    sync.DoSyncProcedure(config, read_only=args.readonly)
  File "/home/circuit/dev/scripts_v2/sync/sync.py", line 189, in DoSyncProcedure
    read_only=read_only)
  File "/home/circuit/dev/scripts_v2/sync/sync.py", line 87, in UpdateLazadaOauth2Tokens
    result.error_description)
sync.common.errors.CommunicationError: Error updating oauth2: The specified refresh token is invalid or expired
